spring:
  profiles:
    active:
  datasource:
    jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/test
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: user
    password: password


server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      force: true

mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.example.springbatch
  configuration:
    multiple-result-sets-enabled: true
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    jdbc-type-for-null: varchar
    default-fetch-size: 1000